### ISSUE TITLE
希望提供现成的账户自动止损功能

### ISSUE THREAD

**Issue by poboquant** [qmhedging/poboquant#34]

**Comment by qmhedging** [comment]
可以用这个清仓函数进行全盘清仓https://github.com/qmhedging/poboquant/blob/master/problems/%E6%B8%85%E4%BB%93%E5%87%BD%E6%95%B0FunctiontoLiquidateAccount
或者使用止盈止损函数 https://quant.pobo.net.cn/doc?name=api#%E6%AD%A2%E6%8D%9F%E6%AD%A2%E7%9B%88
